In [7]:
import numpy as np

X = np.array([
    [3, 5],
    [5, 1],
    [10, 2]
])

y= 75

w1= np.array([[2, 7, 4], [-1, 3, -3]])
w2= np.array([-2, 2, -4])

def relu(X):
    return np.maximum(0, X)

z2 = np.dot(X, w1)
z2

array([[ 1, 36, -3],
       [ 9, 38, 17],
       [18, 76, 34]])

In [8]:
a2=relu(z2)
a2

array([[ 1, 36,  0],
       [ 9, 38, 17],
       [18, 76, 34]])

In [9]:
y_hat = np.dot(a2, w2)
y_hat

array([ 70, -10, -20])

In [11]:
loss = np.square(y_hat - y).mean()
loss

5425.0

In [12]:

loss = np.square((np.dot(relu(np.dot(X, w1)), w2)) - y).mean()
loss

5425.0